services:
    EWZ\SymfonyAdminBundle\Doctrine\UserSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            - '@security.encoder_factory'

    EWZ\SymfonyAdminBundle\EventSubscriber\TimezoneSubscriber:
        tags:
            - { name: kernel.event_listener, event: console.command }
            - { name: kernel.event_listener, event: kernel.request }
        arguments:
            - '@kernel'
            - '@request_stack'
            - '@security.token_storage'
            - '@twig'
            - '%symfony_admin.timezone.database%'
            - '%symfony_admin.timezone.client%'

    symfony_admin.file_uploader.default:
        class: EWZ\SymfonyAdminBundle\FileUploader\FileUploader
        arguments:
            - '@kernel'
            - '@validator'
            - '@translator'
            - '%symfony_admin.mime_types.extensions%'
            - '%symfony_admin.mime_types.types%'
            - '%symfony_admin.max_filesize%'

    EWZ\SymfonyAdminBundle\FileUploader\FileUploaderInterface:
        alias: 'symfony_admin.file_uploader'

    #
    # Controller
    #

    EWZ\SymfonyAdminBundle\Controller\SecurityController:
        public: true
        arguments:
            - '@security.authentication_utils'
            - '@session'
            - '@twig'

    #
    # Form
    #

    EWZ\SymfonyAdminBundle\Form\Type\DateTimePickerType:
        tags:
            - { name: form.type }
        arguments:
            - '@security.token_storage'

    EWZ\SymfonyAdminBundle\Form\Type\AutocompleteType:
        tags:
            - { name: form.type }
        arguments:
            - '@doctrine'

    EWZ\SymfonyAdminBundle\Form\FilterFormType:
        tags:
            - { name: form.type }
        arguments:
            - '@doctrine'
            - '@symfony_admin.report_repository'

    #
    # Twig Extension
    #

    symfony_admin.twig.extension.app_extension:
        class: EWZ\SymfonyAdminBundle\Twig\Extension\AppExtension
        tags:
            - { name: twig.extension }
        arguments:
            - '@twig'
            - '@symfony_admin.file_uploader'

    symfony_admin.twig.extension.repository_extension:
        class: EWZ\SymfonyAdminBundle\Twig\Extension\RepositoryExtension
        tags:
            - { name: twig.extension }
        arguments:
            - '@doctrine'

    symfony_admin.twig.extension.string_extension:
        class: EWZ\SymfonyAdminBundle\Twig\Extension\StringExtension
        tags:
            - { name: twig.extension }
        arguments:
            - '@twig'

    #
    # Cron-Schedule Repository
    #

    symfony_admin.command.cron_command:
        class: EWZ\SymfonyAdminBundle\Command\CronCommand
        tags:
            - { name: console.command, command: "admin:cron" }
        arguments:
            - '@symfony_admin.cron_schedule_repository'

    symfony_admin.command.cron_definitions_load_command:
        class: EWZ\SymfonyAdminBundle\Command\CronDefinitionsLoadCommand
        tags:
            - { name: console.command, command: "admin:cron:definitions:load" }
        arguments:
            - '@symfony_admin.cron_schedule_repository'

    symfony_admin.cron_schedule_repository.default:
        class: EWZ\SymfonyAdminBundle\Repository\CronScheduleRepository
        arguments:
            - '@doctrine'
            - '@security.token_storage'

    EWZ\SymfonyAdminBundle\Repository\CronScheduleRepository:
        alias: 'symfony_admin.cron_schedule_repository'

    #
    # User Repository
    #

    symfony_admin.security.user_provider:
        class: EWZ\SymfonyAdminBundle\Security\UserProvider
        arguments:
            - '@symfony_admin.user_repository'

    symfony_admin.event_subscriber.last_login_subscriber:
        class: EWZ\SymfonyAdminBundle\EventSubscriber\LastLoginSubscriber
        tags:
            - kernel.event_subscriber
        arguments:
            - '@symfony_admin.user_repository'

    symfony_admin.user_repository.default:
        class: EWZ\SymfonyAdminBundle\Repository\UserRepository
        arguments:
            - '@doctrine'
            - '@security.token_storage'
            - '@security.encoder_factory'

    EWZ\SymfonyAdminBundle\Repository\UserRepository:
        alias: 'symfony_admin.user_repository'

    #
    # Report Repository
    #

    symfony_admin.report_repository.default:
        class: EWZ\SymfonyAdminBundle\Repository\ReportRepository
        arguments:
            - '@doctrine'
            - '@security.token_storage'

    EWZ\SymfonyAdminBundle\Repository\ReportRepository:
        alias: 'symfony_admin.report_repository'
